### ISSUE TITLE
Exception viewing app when it's not deployed

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform-control-panel#721]
If you create an app in controlpanel and view it in controlpanel before the app has been deployed (by Concourse) then you get an exception:
https://sentry.service.dsd.io/mojds/control-panel-api/issues/36471/

According to the guidance this is the correct order: https://moj-analytical-services.github.io/platform_user_guidance/deploying-an-r-shiny-app.html#basic-deployment but whatever the order we should probably fail better.

I experienced this on https://github.com/moj-analytical-services/sdt-email
https://controlpanel.services.alpha.mojanalytics.xyz/webapps/125/ "Sorry, there is a problem with the service"
until it was deployed.

--
BTW there seems a related but separate error for the same thing in the old cpanel:
https://controlpanel.services.alpha.mojanalytics.xyz/webapps/125/ "Sorry, there is a problem with the service"
https://sentry.service.dsd.io/mojds/control-panel-frontend/issues/34769/

**Comment by xoen** [comment]
I had a look at this and I think it was somehow fixed by [this commit](https://github.com/ministryofjustice/analytics-platform-control-panel/commit/06daf3cc20219e8f91c376380dc59e73fa5b56b6#diff-cf64d21cec23b2ea57a24847ce87d955R35).

The error `TypeError: object of type 'NoneType' has no len()` is a fancy way of saying the code was expecting a list but got `None`. I *think* the `or []` solves that.

I've also tested this on [an existing test app (`rshiny-test-mikael`)](https://cpanel-master.services.alpha.mojanalytics.xyz/webapps/10/) by deleting the corresponging Auth0 authorisation group and its customers (there was only one). View the application details still works and doesn't raise any exception.

Another piece of evidence is that that exception was last seen 6 months ago on Aug 13, 2019 (10:05:05 AM UTC) and that commit is from the 14th August. 

I'm closing this as it seems revolved.
